# Generated by Django 5.1.5 on 2025-01-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_storeproduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StoreProduct",
        ),
    ]
